### ISSUE TITLE
NameError: name 'inputDevice' is not defined

### ISSUE THREAD

**Issue by maldini89** [jmatg1/lords-mobile-bot#4]
Traceback (most recent call last):
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\lords-mobile-bot-main\code.py", line 320, in start
    self.device = inputDevice.get()
NameError: name 'inputDevice' is not defined

**Comment by jmatg1** [comment]
show me screen window

**Comment by maldini89** [comment]
![image](https://user-images.githubusercontent.com/31111256/221935851-427e61e9-229b-4a02-8288-003440e89e27.png)

**Comment by jmatg1** [comment]
Do you have discord? add me ribrush#9877

**Comment by maldini89** [comment]
Yes, I have. But I can't find you, because you have disabled the option to add friends and I don't have any common channels with you %)

**Comment by jmatg1** [comment]
Need install Python **3.9.1**
