### ISSUE TITLE
Question about the Instruction

### ISSUE THREAD

**Issue by deerhounds-me** [jmatg1/lords-mobile-bot#5]
hello, can you explain what does below instruction mean?

Settings Windows
Add path C:\Program Files\BlueStacks\ (Default Path) on the Environment Windows
or Change hd-adb in the code to C:\Program Files\BlueStacks\hd-adb.exe

I got error FileNotFoundError: [WinError 2] The system cannot find the file specified when running the code.py
![error](https://github.com/jmatg1/lords-mobile-bot/assets/66994107/e12128a3-ff0e-424f-9cf8-f3fb9897eb9a)

Really appreciate it if you can give me explaination. Thanks in advance!

**Comment by jmatg1** [comment]
YOu need istall pyton Python 3.9.1 https://www.python.org/downloads/release/python-391/
3.9.1 version important
and bot it doesnt work, because game updated and it have new graph

**Comment by KareemOsamaAnwar** [comment]
> YOu need istall pyton Python 3.9.1 https://www.python.org/downloads/release/python-391/ 3.9.1 version important and bot it doesnt work, because game updated and it have new graph

Do you intent to update it?

**Comment by jmatg1** [comment]
> > YOu need istall pyton Python 3.9.1 https://www.python.org/downloads/release/python-391/ 3.9.1 version important and bot it doesnt work, because game updated and it have new graph
> 
> Do you intent to update it?

For money - yes
